/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JAVA_SE_1_BAITAP2;

import java.util.Scanner;

/**
 *
 * @author ADMIN
 */
public class BAITAP_2_4_FRAME extends javax.swing.JFrame {

    /**
     * Creates new form BAITAP_2_4_FRAME
     */
    public BAITAP_2_4_FRAME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSoTienGoi = new javax.swing.JTextField();
        lblSoTienGoi = new javax.swing.JLabel();
        lblSoThangGoi = new javax.swing.JLabel();
        lblLaiXuatNam = new javax.swing.JLabel();
        lblSoTienLoi = new javax.swing.JLabel();
        txtSoThangGoi = new javax.swing.JTextField();
        txtLaiXuatNam = new javax.swing.JTextField();
        lblTongTienNhan = new javax.swing.JLabel();
        btnTinhTien = new javax.swing.JButton();
        txtXuatTienLoi = new javax.swing.JTextField();
        txtXuatTongTien = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSoTienGoi.setText("So tien goi");

        lblSoThangGoi.setText("So Thang Goi");

        lblLaiXuatNam.setText("Lai Xuat nam");

        lblSoTienLoi.setText("So tien loi");

        lblTongTienNhan.setText("Tong tien nhan");

        btnTinhTien.setText("Tinh Tien");
        btnTinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienActionPerformed(evt);
            }
        });

        txtXuatTienLoi.setEditable(false);
        txtXuatTienLoi.setText("jTextField1");

        txtXuatTongTien.setEditable(false);
        txtXuatTongTien.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSoTienGoi)
                            .addComponent(lblSoThangGoi)
                            .addComponent(lblLaiXuatNam)
                            .addComponent(lblSoTienLoi)
                            .addComponent(lblTongTienNhan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLaiXuatNam)
                            .addComponent(txtSoThangGoi)
                            .addComponent(txtSoTienGoi)
                            .addComponent(txtXuatTienLoi, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txtXuatTongTien)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnTinhTien)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoTienGoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoTienGoi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoThangGoi)
                    .addComponent(txtSoThangGoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLaiXuatNam)
                    .addComponent(txtLaiXuatNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoTienLoi)
                    .addComponent(txtXuatTienLoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongTienNhan)
                    .addComponent(txtXuatTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnTinhTien)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienActionPerformed
        // TODO add your handling code here:
        double soTienLoi = Double.parseDouble(txtSoTienGoi.getText())*
                Integer.parseInt(txtSoThangGoi.getText())*
                Float.parseFloat(txtLaiXuatNam.getText())/100/12;
        double soTongSoTien=Double.parseDouble(txtSoTienGoi.getText())+soTienLoi;
        
        txtXuatTienLoi.setText(String.format("%.2f",soTienLoi));
        txtXuatTongTien.setText(String.format("%.2f",soTongSoTien));
    }//GEN-LAST:event_btnTinhTienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BAITAP_2_4_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BAITAP_2_4_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BAITAP_2_4_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BAITAP_2_4_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BAITAP_2_4_FRAME().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTinhTien;
    private javax.swing.JLabel lblLaiXuatNam;
    private javax.swing.JLabel lblSoThangGoi;
    private javax.swing.JLabel lblSoTienGoi;
    private javax.swing.JLabel lblSoTienLoi;
    private javax.swing.JLabel lblTongTienNhan;
    private javax.swing.JTextField txtLaiXuatNam;
    private javax.swing.JTextField txtSoThangGoi;
    private javax.swing.JTextField txtSoTienGoi;
    private javax.swing.JTextField txtXuatTienLoi;
    private javax.swing.JTextField txtXuatTongTien;
    // End of variables declaration//GEN-END:variables
}
