/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JAVA_SE_1_PHUONGTHUC;

import javax.swing.ImageIcon;

/**
 *
 * @author ADMIN
 */
public class BAITAP_7_4 extends javax.swing.JFrame {

    /**
     * Creates new form BAITAP_7_4
     */
    
    String tenHinh="";
    
    public static String tinhCan(int year){
    int can = year%10;
    String txtCan="";
    
    switch(can){
            case 0: txtCan="Canh";break;
            case 1: txtCan="Tan";break;
            case 2: txtCan="Nham";break;
            case 3: txtCan="Quy";break;
            case 4: txtCan="Giap";break;
            case 5: txtCan="At";break;
            case 6: txtCan="Binh";break;
            case 7: txtCan="Dinh";break;
            case 8: txtCan="Mau";break;
            case 9: txtCan="Ky";break;
    }
    return txtCan;
    }
    
    
    public String tinhChi(int year){
    int chi =year%12;
    String txtChi="";
    
    switch (chi){
      case 0: txtChi="Than"; break;
            case 1: txtChi="Dau"; tenHinh="dau"; break;
            case 2: txtChi="Tuat";tenHinh="tuat"; break;
            case 3: txtChi="Hoi"; tenHinh="hoi";break;
            case 4: txtChi="Ty"; tenHinh="ty";break;
            case 5: txtChi="Suu"; tenHinh="suu";break;
            case 6: txtChi="Dan"; tenHinh="dan";break;
            case 7: txtChi="mao"; tenHinh="mao";break;
            case 8: txtChi="Thin"; tenHinh="thin";break;
            case 9: txtChi="Ty"; tenHinh="ty";break;
            case 10: txtChi="Ngo"; tenHinh="ngo";break;
            case 11: txtChi="Mui"; tenHinh="mui";break;
    
    }
    return txtChi;
    }
    
    public BAITAP_7_4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblYear = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        lblHinh = new javax.swing.JLabel();
        lblXuatNam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblYear.setText("Year of birth");

        btnOK.setText("Tinh");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblYear)
                        .addGap(33, 33, 33)
                        .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnOK)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblXuatNam, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnOK)
                .addGap(35, 35, 35)
                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblXuatNam, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        int year = Integer.parseInt(txtYear.getText());
        lblXuatNam.setText(tinhCan(year)+ " " +tinhChi(year));
        
        lblHinh.setIcon(new ImageIcon("src/12congiap/"+tenHinh+".jpg"));
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BAITAP_7_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BAITAP_7_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BAITAP_7_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BAITAP_7_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BAITAP_7_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblXuatNam;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
