/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ngay7_ResourceBundle;

import java.util.Enumeration;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.DefaultListModel;

/**
 *
 * @author hv
 */
public class frmVeMayBay extends javax.swing.JFrame {

    /**
     * Creates new form frmVeMayBay
     */
    
    Locale currentLocale;
    ResourceBundle resource;
    String vn="resource_vi_VN";
    String en ="resource_en_US";
    
    
    public void showResouce (){
        DefaultListModel ListModel = new DefaultListModel();
        Enumeration<String> keys = resource.getKeys();
        while (keys.hasMoreElements()){
        String key = keys.nextElement();
        String value = resource.getString(key);
        ListModel.addElement(value);
        }
        lstXuat.setModel(ListModel);
    }
    
    
    public frmVeMayBay() {
        initComponents();
        
        currentLocale= new Locale("vi", "VN");
        resource= ResourceBundle.getBundle("Ngay7_ResourceBundle/resource_vi_VN", currentLocale);
        showResouce();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbtVN = new javax.swing.JRadioButton();
        rbtEN = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstXuat = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Chon Ngon Ngu");

        buttonGroup1.add(rbtVN);
        rbtVN.setSelected(true);
        rbtVN.setText("Vietnamese");
        rbtVN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtVNActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtEN);
        rbtEN.setText("English");
        rbtEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtENActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstXuat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(92, 92, 92)
                        .addComponent(rbtVN)
                        .addGap(83, 83, 83)
                        .addComponent(rbtEN)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rbtVN)
                    .addComponent(rbtEN))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtVNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtVNActionPerformed
        // TODO add your handling code here:
        
        currentLocale= new Locale("vi", "VN");
        resource= ResourceBundle.getBundle("Ngay7_ResourceBundle/resource_vi_VN", currentLocale);
        showResouce();
        
    }//GEN-LAST:event_rbtVNActionPerformed

    private void rbtENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtENActionPerformed
        // TODO add your handling code here:
        currentLocale= new Locale("en", "US");
        resource= ResourceBundle.getBundle("Ngay7_ResourceBundle/resource_en_US", currentLocale);
        showResouce();
        
        
    }//GEN-LAST:event_rbtENActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVeMayBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVeMayBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVeMayBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVeMayBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVeMayBay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstXuat;
    private javax.swing.JRadioButton rbtEN;
    private javax.swing.JRadioButton rbtVN;
    // End of variables declaration//GEN-END:variables
}
