/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ngay3;

/**
 *
 * @author hv
 */
public class Bai3_1 extends javax.swing.JFrame {

    /**
     * Creates new form Bai3_1
     */
    public Bai3_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTronBanKinh = new javax.swing.JTextField();
        txtTronChuVi = new javax.swing.JTextField();
        txtTronDienTich = new javax.swing.JTextField();
        btnTronTinhChuVi = new javax.swing.JButton();
        btnTronTinhDienTich = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCNDai = new javax.swing.JTextField();
        txtCNRong = new javax.swing.JTextField();
        txtCNChuVi = new javax.swing.JTextField();
        txtCNDienTich = new javax.swing.JTextField();
        btnCNTinhChuVi = new javax.swing.JButton();
        btnCNTinhDienTich = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtVuongCanh = new javax.swing.JTextField();
        txtVuongChuVi = new javax.swing.JTextField();
        txtVuongDienTich = new javax.swing.JTextField();
        btnVuongTinhChuVi = new javax.swing.JButton();
        btnVuongTinhDienTich = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ban Kinh");

        jLabel2.setText("ChuVi");

        jLabel3.setText("Dien Tich");

        txtTronChuVi.setEditable(false);

        txtTronDienTich.setEditable(false);

        btnTronTinhChuVi.setText("Tinh Chu Vi");
        btnTronTinhChuVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTronTinhChuViActionPerformed(evt);
            }
        });

        btnTronTinhDienTich.setText("Tinh Dien Tich");
        btnTronTinhDienTich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTronTinhDienTichActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTronBanKinh, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(txtTronChuVi)
                    .addComponent(txtTronDienTich))
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTronTinhChuVi)
                    .addComponent(btnTronTinhDienTich))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTronBanKinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTronTinhChuVi))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTronChuVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTronTinhDienTich)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTronDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hinh Tron", jPanel1);

        jLabel4.setText("Chieu Dai");

        jLabel5.setText("Chieu Rong");

        jLabel6.setText("Chu Vi");

        jLabel7.setText("Dien Tich");

        txtCNChuVi.setEditable(false);

        txtCNDienTich.setEditable(false);

        btnCNTinhChuVi.setText("Tinh Chu vi");
        btnCNTinhChuVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCNTinhChuViActionPerformed(evt);
            }
        });

        btnCNTinhDienTich.setText("Tinh dien tich");
        btnCNTinhDienTich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCNTinhDienTichActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCNDai)
                    .addComponent(txtCNRong)
                    .addComponent(txtCNChuVi)
                    .addComponent(txtCNDienTich, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCNTinhChuVi)
                    .addComponent(btnCNTinhDienTich))
                .addGap(109, 109, 109))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCNDai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCNRong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnCNTinhChuVi)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCNChuVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnCNTinhDienTich)))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtCNDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hinh CHu Nhat", jPanel2);

        jLabel8.setText("Canh");

        jLabel9.setText("Chu VI");

        jLabel10.setText("Dien Tich");

        txtVuongCanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVuongCanhActionPerformed(evt);
            }
        });

        txtVuongChuVi.setEditable(false);

        txtVuongDienTich.setEditable(false);
        txtVuongDienTich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVuongDienTichActionPerformed(evt);
            }
        });

        btnVuongTinhChuVi.setText("Tinh Chu vi");
        btnVuongTinhChuVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVuongTinhChuViActionPerformed(evt);
            }
        });

        btnVuongTinhDienTich.setText("Tinh dien tich");
        btnVuongTinhDienTich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVuongTinhDienTichActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(73, 73, 73)
                        .addComponent(txtVuongCanh, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVuongChuVi)
                            .addComponent(txtVuongDienTich))))
                .addGap(332, 332, 332))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVuongTinhDienTich)
                    .addComponent(btnVuongTinhChuVi))
                .addGap(124, 124, 124))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtVuongCanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(btnVuongTinhChuVi)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtVuongChuVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnVuongTinhDienTich)
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtVuongDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hinh Vuong", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVuongCanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVuongCanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVuongCanhActionPerformed

    private void txtVuongDienTichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVuongDienTichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVuongDienTichActionPerformed

    private void btnTronTinhChuViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTronTinhChuViActionPerformed
        // TODO add your handling code here:
        float r = Float.parseFloat(txtTronBanKinh.getText());
        HinhTron tron = new HinhTron(r);
        txtTronChuVi.setText(String.format("%.2f",tron.chuVi()));
        
        
    }//GEN-LAST:event_btnTronTinhChuViActionPerformed

    private void btnTronTinhDienTichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTronTinhDienTichActionPerformed
        // TODO add your handling code here:
        float r = Float.parseFloat(txtTronBanKinh.getText());
        HinhTron tron = new HinhTron(r);
        txtTronDienTich.setText(String.format("%.2f",tron.dienTich()));
    }//GEN-LAST:event_btnTronTinhDienTichActionPerformed

    private void btnCNTinhChuViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCNTinhChuViActionPerformed
        // TODO add your handling code here:
        float d= Float.parseFloat(txtCNDai.getText());
        float r= Float.parseFloat(txtCNRong.getText());
        HinhChuNhat cn = new HinhChuNhat(d, r);
        txtCNChuVi.setText(String.format("%.2f",cn.chuVi()));
        
    }//GEN-LAST:event_btnCNTinhChuViActionPerformed

    private void btnCNTinhDienTichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCNTinhDienTichActionPerformed
        // TODO add your handling code here:
        float d= Float.parseFloat(txtCNDai.getText());
        float r= Float.parseFloat(txtCNRong.getText());
        HinhChuNhat cn = new HinhChuNhat(d, r);
        txtCNDienTich.setText(String.format("%.2f",cn.dienTich()));
        
    }//GEN-LAST:event_btnCNTinhDienTichActionPerformed

    private void btnVuongTinhChuViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVuongTinhChuViActionPerformed
        // TODO add your handling code here:
         float canh = Float.parseFloat(txtVuongCanh.getText());
         HinhVuong v = new HinhVuong(canh);
         txtVuongChuVi.setText(String.format("%.2f",v.chuVi()));
        
    }//GEN-LAST:event_btnVuongTinhChuViActionPerformed

    private void btnVuongTinhDienTichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVuongTinhDienTichActionPerformed
        // TODO add your handling code here:
        float canh = Float.parseFloat(txtVuongCanh.getText());
         HinhVuong v = new HinhVuong(canh);
         txtVuongDienTich.setText(String.format("%.2f",v.dienTich()));
        
    }//GEN-LAST:event_btnVuongTinhDienTichActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai3_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCNTinhChuVi;
    private javax.swing.JButton btnCNTinhDienTich;
    private javax.swing.JButton btnTronTinhChuVi;
    private javax.swing.JButton btnTronTinhDienTich;
    private javax.swing.JButton btnVuongTinhChuVi;
    private javax.swing.JButton btnVuongTinhDienTich;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtCNChuVi;
    private javax.swing.JTextField txtCNDai;
    private javax.swing.JTextField txtCNDienTich;
    private javax.swing.JTextField txtCNRong;
    private javax.swing.JTextField txtTronBanKinh;
    private javax.swing.JTextField txtTronChuVi;
    private javax.swing.JTextField txtTronDienTich;
    private javax.swing.JTextField txtVuongCanh;
    private javax.swing.JTextField txtVuongChuVi;
    private javax.swing.JTextField txtVuongDienTich;
    // End of variables declaration//GEN-END:variables
}
