/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ngay1;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author hv
 */
public class Bai1_3_toantuJava extends javax.swing.JFrame {

    /**
     * Creates new form Bai1_3_toantuJava
     */
    //Nhom Toan Tu
        Bai1_3_operator cong = (s1, s2)->s1+s2;
        Bai1_3_operator tru = (s1, s2)->s1-s2;
        Bai1_3_operator nhan = (s1, s2)->s1*s2;
        Bai1_3_operator chia = (s1, s2)->s1/s2;
        Bai1_3_operator chiadu = (s1, s2)->s1%s2;
        
        
    //Nhom Lon nho
        public void sosanh(int so1, int so2){
            if(so1>so2)
                txtKetQua.setText(so1 + " lon hon "+ so2);
            else if(so1<so2)
                txtKetQua.setText(so1 + " be hon "+ so2);
            else
                txtKetQua.setText(so1 + " bang "+ so2);
    }
        
        
        
        
    public Bai1_3_toantuJava() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbNhom = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbToanTu = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSo1 = new javax.swing.JTextField();
        txtSo2 = new javax.swing.JTextField();
        txtKetQua = new javax.swing.JTextField();
        btnTinh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbNhom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "------Chọn------", "So Hoc", "Quan He", "Lan Ly", "Dich Bit" }));
        cbNhom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNhomActionPerformed(evt);
            }
        });

        jLabel1.setText("Nhom Toan");

        jLabel2.setText("Toan Tu");

        cbToanTu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-----Chọn-----" }));
        cbToanTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbToanTuActionPerformed(evt);
            }
        });

        jLabel3.setText("Toan hang 1");

        jLabel4.setText("Toan hang 2");

        jLabel5.setText("Ket Qua");

        btnTinh.setText("Tinh");
        btnTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbNhom, 0, 122, Short.MAX_VALUE)
                            .addComponent(cbToanTu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKetQua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnTinh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNhom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbToanTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTinh)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbNhomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNhomActionPerformed
        // TODO add your handling code here:
        String [] list = null;
        if(cbNhom.getSelectedIndex()==0){
            list = new String[1];
            ComboBoxModel cboModel = new DefaultComboBoxModel(list);
            cbToanTu.setModel(cboModel);
        }
        else if(cbNhom.getSelectedIndex()==1){
            list = new String[5];
            list[0]="Cộng \"+\"";
            list[1]="Trừ \"-\"";
            list[2]="Nhân \"*\"";
            list[3]="Chia Dư \"/\"";
            list[4]="Chia Nguyên \"%\"";
            ComboBoxModel cboModel = new DefaultComboBoxModel(list);
            cbToanTu.setModel(cboModel);
            
        }else if(cbNhom.getSelectedIndex()==2){
            list = new String[3];
            list[0]="Lớn \">\"";
            list[1]="Bé \"<\"";
            list[2]="Bằng \"=\"";
            DefaultComboBoxModel cboModel= new DefaultComboBoxModel(list);
            cbToanTu.setModel(cboModel);
            
        }else if(cbNhom.getSelectedIndex()==3){
            list = new String[2];
            list[0]="And \"&&\"";
            list[1]="Or \"||\"";
            DefaultComboBoxModel cboModel= new DefaultComboBoxModel(list);
            cbToanTu.setModel(cboModel);
        }
    }//GEN-LAST:event_cbNhomActionPerformed

    private void cbToanTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbToanTuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbToanTuActionPerformed

    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed
        // TODO add your handling code here:
        try{
        int so1= Integer.parseInt(txtSo1.getText());
        int so2= Integer.parseInt(txtSo2.getText());
        
        switch (cbNhom.getSelectedIndex()){
            case 1:
                switch (cbToanTu.getSelectedIndex()){
                    case 0: txtKetQua.setText(String.format("%.0f",cong.operator(so1, so2)));break;
                    case 1: txtKetQua.setText(String.format("%.0f",tru.operator(so1, so2)));break;
                    case 2: txtKetQua.setText(String.format("%.0f",nhan.operator(so1, so2)));break;
                    case 3: txtKetQua.setText(String.format("%.0f",chia.operator(so1, so2)));break;
                    case 4: txtKetQua.setText(String.format("%.0f",chiadu.operator(so1, so2)));break;
                    default: JOptionPane.showMessageDialog(rootPane, "Moi chon toan tu");break;
            }break;
            case 2:
                    sosanh(so1, so2);break;
            case 3: case 4:
                    JOptionPane.showMessageDialog(rootPane, "Chuc nag chua Dev");break;
                    
            default:
                    JOptionPane.showMessageDialog(rootPane, "Moi chon Nhom");break;
        }
           
        
       
        }   catch (NumberFormatException ex){
                JOptionPane.showMessageDialog(rootPane, "Moi Nhap so");
        }
        
            
        
        
        
        
    }//GEN-LAST:event_btnTinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai1_3_toantuJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai1_3_toantuJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai1_3_toantuJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai1_3_toantuJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai1_3_toantuJava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTinh;
    private javax.swing.JComboBox cbNhom;
    private javax.swing.JComboBox cbToanTu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtKetQua;
    private javax.swing.JTextField txtSo1;
    private javax.swing.JTextField txtSo2;
    // End of variables declaration//GEN-END:variables
}
