/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JAVA_SE_1_BAITAP8_LOP;

import javax.swing.ImageIcon;

/**
 *
 * @author QAVN
 */
public class BAITAP_8_2_Form extends javax.swing.JFrame {

    /**
     * Creates new form BAITAP_8_2_Form
     */
    
    BAITAP_8_2_Phim[] dsPhim = new BAITAP_8_2_Phim[5];
    int index=0;
    
    
    
    public BAITAP_8_2_Form() {
        initComponents();
        String link ="src/hinhPhim/";
        
        dsPhim[0]=new BAITAP_8_2_Phim("Chim cánh cụt", "Hoạt Hình", "08/03/2017", "Rap 1", link+"Chim_canhcut.jpeg");
        dsPhim[1]=new BAITAP_8_2_Phim("Doraemon", "Hoạt Hình", "09/03/2017", "Rạp 2", link+"Doremon.jpeg");
        dsPhim[2]=new BAITAP_8_2_Phim("Elsa", "Hoạt Hình", "10/03/2017", "Rạp 3", link+"Elsa.jpeg");
        dsPhim[3]=new BAITAP_8_2_Phim("Lion King", "Hoạt Hình", "11/03/2017", "Rạp 4", link+"Lion_King.jpeg");
        dsPhim[4]=new BAITAP_8_2_Phim("Naruto", "Hoạt Hình", "12/03/2017", "Rạp 5", link+"Naruto.jpeg");
        
        lblLink.setIcon(new ImageIcon(dsPhim[0].link));
        lblTenPhim.setText(dsPhim[0].tenPhim);
        lblTheLoai.setText(dsPhim[0].theLoai);
        lblDateTime.setText(dsPhim[0].dateTime);
        lblTenRap.setText(dsPhim[0].tenRap);
        
        btnLeft.setIcon(new ImageIcon(link +"left.png"));
        btnRight.setIcon(new ImageIcon(link+"right.png"));
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLink = new javax.swing.JLabel();
        lblTenPhim = new javax.swing.JLabel();
        lblTheLoai = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        lblTenRap = new javax.swing.JLabel();
        btnLeft = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLink.setText("jLabel1");

        lblTenPhim.setText("jLabel2");

        lblTheLoai.setText("jLabel3");

        lblDateTime.setText("jLabel4");

        lblTenRap.setText("jLabel5");

        btnLeft.setText("jButton1");
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });

        btnRight.setText("jButton2");
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblLink, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTenPhim, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(lblTheLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDateTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTenRap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTenPhim)
                        .addGap(28, 28, 28)
                        .addComponent(lblTheLoai)
                        .addGap(27, 27, 27)
                        .addComponent(lblDateTime)
                        .addGap(31, 31, 31)
                        .addComponent(lblTenRap))
                    .addComponent(lblLink, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRight, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(btnLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        // TODO add your handling code here:
        //Nút left
        
        if (index>0){
        index --;
        
        lblLink.setIcon(new ImageIcon(dsPhim[index].link));
        lblTenPhim.setText(dsPhim[index].tenPhim);
        lblTheLoai.setText(dsPhim[index].theLoai);
        lblDateTime.setText(dsPhim[index].dateTime);
        lblTenRap.setText(dsPhim[index].tenRap);
        
        }
        
        
    }//GEN-LAST:event_btnLeftActionPerformed

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        // TODO add your handling code here:
        // Nút Right
        if (index <4){
        index ++;
        
        lblLink.setIcon(new ImageIcon(dsPhim[index].link));
        lblTenPhim.setText(dsPhim[index].tenPhim);
        lblTheLoai.setText(dsPhim[index].theLoai);
        lblDateTime.setText(dsPhim[index].dateTime);
        lblTenRap.setText(dsPhim[index].tenRap);
        
        }
        
    }//GEN-LAST:event_btnRightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BAITAP_8_2_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BAITAP_8_2_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BAITAP_8_2_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BAITAP_8_2_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BAITAP_8_2_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnRight;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblLink;
    private javax.swing.JLabel lblTenPhim;
    private javax.swing.JLabel lblTenRap;
    private javax.swing.JLabel lblTheLoai;
    // End of variables declaration//GEN-END:variables
}
