/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JAVA_SE_1_BAITAP5_VONGLAP;

/**
 *
 * @author hv
 */
public class BAITAP_CTLAP_2 extends javax.swing.JFrame {

    /**
     * Creates new form BAITAP_CTLAP_2
     */
    public BAITAP_CTLAP_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLabel = new javax.swing.JLabel();
        lblTien = new javax.swing.JLabel();
        txtTien = new javax.swing.JTextField();
        btnDoiTien = new javax.swing.JButton();
        txtaXuat = new javax.swing.JScrollPane();
        txtaXuat1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLabel.setText("Soft doi tien");

        lblTien.setText("So tien");

        btnDoiTien.setText("DoiTien");
        btnDoiTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiTienActionPerformed(evt);
            }
        });

        txtaXuat1.setColumns(20);
        txtaXuat1.setRows(5);
        txtaXuat.setViewportView(txtaXuat1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTien)
                                .addGap(57, 57, 57)
                                .addComponent(txtTien, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnDoiTien))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtaXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLabel)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTien)
                    .addComponent(txtTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnDoiTien)
                .addGap(26, 26, 26)
                .addComponent(txtaXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoiTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiTienActionPerformed
        // TODO add your handling code here:
        
        int tien = Integer.parseInt(txtTien.getText());
        int soTo, loaiTo=0; //100k, 50k, 20k, 10k, 5k, 2k, 1k
        String text="";
        
        for (int i=1; i<=7; i++){
            switch(i){
                case 1: loaiTo=100000; break;
                case 2: loaiTo=50000; break;
                case 3: loaiTo=20000; break;
                case 4: loaiTo=10000; break;
                case 5: loaiTo=5000; break;
                case 6: loaiTo=2000; break;
                case 7: loaiTo=1000; break;    
            }
            soTo=tien/loaiTo;
            tien=tien%loaiTo;
            if (soTo>0)
            text += soTo+ "to" + loaiTo + "vnd\n";
           
        }
        
        txtaXuat1.setText(text);
        
    }//GEN-LAST:event_btnDoiTienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BAITAP_CTLAP_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BAITAP_CTLAP_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BAITAP_CTLAP_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BAITAP_CTLAP_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BAITAP_CTLAP_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiTien;
    private javax.swing.JLabel lblLabel;
    private javax.swing.JLabel lblTien;
    private javax.swing.JTextField txtTien;
    private javax.swing.JScrollPane txtaXuat;
    private javax.swing.JTextArea txtaXuat1;
    // End of variables declaration//GEN-END:variables
}
