/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ngay2;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class Bai_2_3_GiaoDich_Form extends javax.swing.JFrame {

    /**
     * Creates new form Bai_2_3_GiaoDich_Form
     */
    
    List <Bai_2_3_GiaoDich> listVang = new ArrayList<>();
    List <Bai_2_3_GiaoDich_Tien> listTien = new ArrayList<>();
    DefaultListModel  modelVang= new DefaultListModel<>();
    DefaultListModel  modelTien = new DefaultListModel<>();
    double tongTTVang=0, tongTTTien=0;
    int tongSLVang =0, tongSLTien=0;
    static double tongTTVang1=0, tongTTTien1=0; //Biến tĩnh dùng chung
    static int tongSLVang1 =0, tongSLTien1=0; //Biến Tĩnh dùng chung
    
    
    
    public void thongKeVang(List<Bai_2_3_GiaoDich> listVang){
        boolean tim=false;
    for(Bai_2_3_GiaoDich vang:this.listVang){
        
        if(cbbVang_ThongKeLoai.getSelectedItem().toString().equalsIgnoreCase(vang.getLoai())){
            tim=true;
            tongSLVang+=vang.soLuong;
            tongTTVang+=vang.ThanhTien();
        }
        }
        txtVang_TongSL.setText(tongSLVang+"");
        txtVang_ThanhTien.setText(tongTTVang+"");
    if(tim==false){
        JOptionPane.showMessageDialog(this, "Loại vàng này chưa có giao dịch");
//        this.listVang.stream().map((vang) -> {
//            tongSLVang+=vang.soLuong;
//                return vang;
//            }).forEachOrdered((vang) -> {
//                tongTTVang+=vang.ThanhTien();
//            });
//        txtVang_TongSL.setText(tongSLVang+"");
//        txtVang_ThanhTien.setText(tongTTVang+"");
    }
    
//    if(tim==false){
//        for(Bai_2_3_GiaoDich vang:this.listVang){
//        tongSLVang+=vang.soLuong;
//        tongTTVang+=vang.ThanhTien();
//        }
//        txtVang_TongSL.setText(tongSLVang+"");
//        txtVang_ThanhTien.setText(tongTTVang+"");
//    }
//    else{
//    tongSLVang+=vang.soLuong;
//    tongTTVang+=vang.ThanhTien();
//    }
    
        
    }
    
    public void thongKeVangTotal(List<Bai_2_3_GiaoDich> listVang){
        this.listVang.stream().map((vang) -> {
            tongSLVang+=vang.soLuong;
            return vang;
        }).forEachOrdered((vang) -> {
            tongTTVang+=vang.ThanhTien();
        });//Vòng lập máy tự convert theo cách viết function
        txtVang_TongSL.setText(tongSLVang+"");
        txtVang_ThanhTien.setText(tongTTVang+"");
    }
    
    public void thongKeTien(List<Bai_2_3_GiaoDich_Tien> listTien, String loaiGD, String loaiTien){

        boolean tim = false;
        //Thong kê theo mua
        
        for (Bai_2_3_GiaoDich_Tien tien:listTien)
        {
            if(loaiTien.equalsIgnoreCase(tien.getLoai())
                    &&loaiGD.equalsIgnoreCase(tien.loaiGD))
            {
            tim=true;
            tongSLTien+=tien.soLuong;
            tongTTTien+=tien.ThanhTien();
            }
            txtTien_XuatTongSL.setText(tongSLTien+"");
            txtTien_TongThanhTien.setText(tongTTTien+"");
        }
        if (tim==false){
            JOptionPane.showMessageDialog(this, "Loai Tien nay chua dc GD test");
        }
    
    }
    
    public void thongKeTienToTal(List<Bai_2_3_GiaoDich_Tien> listTien, String loaiGD){

        boolean tim = false;
        for(Bai_2_3_GiaoDich_Tien tien:listTien){
            if(loaiGD.equalsIgnoreCase(tien.loaiGD)){
            
            tim=true;
            tongSLTien+=tien.soLuong;
            tongTTTien+=tien.ThanhTien();
            }
            txtTien_XuatTongSL.setText(tongSLTien+"");
            txtTien_TongThanhTien.setText(tongTTTien+"");
        }
            if (tim==false){
            JOptionPane.showMessageDialog(this, "Hom nay khong co GD nay");
        }
            
        
    }
    
    
    public Bai_2_3_GiaoDich_Form() {
        initComponents();
        lstVang_Xuat.setModel(modelVang);
        lstTien_Xuat.setModel(modelTien);
        txtVang_TongSL.setText("0");
        txtVang_ThanhTien.setText("0");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaGD = new javax.swing.JTextField();
        txtSL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtVang_ThemMoi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstVang_Xuat = new javax.swing.JList<String>();
        jLabel10 = new javax.swing.JLabel();
        txtVang_TongSL = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtVang_ThanhTien = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbbVang_ThongKeLoai = new javax.swing.JComboBox<String>();
        cbbVang_NhapLoai = new javax.swing.JComboBox<String>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbbTien_NhapLoai = new javax.swing.JComboBox<String>();
        cbbTien_MuaBan = new javax.swing.JComboBox<String>();
        cbbTien_ThemMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTien_Xuat = new javax.swing.JList<String>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTien_XuatTongSL = new javax.swing.JTextField();
        txtTien_TongThanhTien = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbbTien_ThongKeLoai = new javax.swing.JComboBox<String>();
        jLabel14 = new javax.swing.JLabel();
        cbbTien_ThongKeGD = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("So Luong");

        jLabel3.setText("Date");

        jLabel4.setText("Exchange Rate");

        jLabel9.setText("Loai Vang");

        txtVang_ThemMoi.setText("ThemMoi");
        txtVang_ThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVang_ThemMoiActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstVang_Xuat);

        jLabel10.setText("Tong SL");

        jLabel11.setText("ThanhTien");

        jLabel12.setText("ThongKe");

        cbbVang_ThongKeLoai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Total", "9999", "18k", "16k", "14k" }));
        cbbVang_ThongKeLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbVang_ThongKeLoaiActionPerformed(evt);
            }
        });

        cbbVang_NhapLoai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9999", "18k", "16k", "14k" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(cbbVang_NhapLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtVang_ThemMoi)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbVang_ThongKeLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtVang_TongSL, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(91, 91, 91)
                                        .addComponent(jLabel11)
                                        .addGap(30, 30, 30)
                                        .addComponent(txtVang_ThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtVang_ThemMoi)
                    .addComponent(cbbVang_NhapLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbbVang_ThongKeLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtVang_TongSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtVang_ThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("GD Vang", jPanel1);

        jLabel5.setText("Loai tien te");

        jLabel6.setText("LoaiGD");

        cbbTien_NhapLoai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "USD", "EUR", "AUD" }));

        cbbTien_MuaBan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mua", "Ban" }));

        cbbTien_ThemMoi.setText("Them");
        cbbTien_ThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTien_ThemMoiActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstTien_Xuat);

        jLabel7.setText("Tong SL");

        jLabel8.setText("ThanhTien");

        jLabel13.setText("ThongKe");

        cbbTien_ThongKeLoai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Total", "USD", "EUR", "AUD" }));
        cbbTien_ThongKeLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTien_ThongKeLoaiActionPerformed(evt);
            }
        });

        jLabel14.setText("LoaiGD");

        cbbTien_ThongKeGD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mua", "Ban" }));
        cbbTien_ThongKeGD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTien_ThongKeGDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(42, 42, 42)
                        .addComponent(cbbTien_NhapLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32)
                        .addComponent(cbbTien_MuaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(cbbTien_ThemMoi)))
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel7))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTien_XuatTongSL)
                    .addComponent(cbbTien_ThongKeLoai, 0, 84, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTien_TongThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTien_ThongKeGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(cbbTien_NhapLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTien_MuaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTien_ThemMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbbTien_ThongKeLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cbbTien_ThongKeGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtTien_XuatTongSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTien_TongThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("GD Tien Te", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaGD, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(txtSL))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVang_ThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVang_ThemMoiActionPerformed
        // TODO add your handling code here:
        
        try {
        String maGD = txtMaGD.getText();
        int soLuong = Integer.parseInt(txtSL.getText());
        double rate = Double.parseDouble(txtRate.getText());
        Date ngay = FormatDate.stringToDate(txtDate.getText());
        String loaiVang = cbbVang_NhapLoai.getSelectedItem().toString();
        //String loaiTien = cbbTien_NhapLoai.getSelectedItem().toString();
        //String loaiGD = cbbTien_MuaBan.getSelectedItem().toString();
        Bai_2_3_GiaoDich gdVang = new Bai_2_3_GiaoDich(maGD, soLuong, rate, ngay, loaiVang);
        listVang.add(gdVang);
        modelVang.addElement(gdVang.toString());
        tongSLVang+=gdVang.soLuong;
        tongTTVang+=gdVang.ThanhTien();
        tongSLVang1+=gdVang.soLuong; //Biến Tĩnh share qua bên thống kê
        tongTTVang1+=gdVang.ThanhTien();// Biến Tĩnh share qua bên thống kê
        txtVang_ThanhTien.setText(String.format("%.0f",tongTTVang));
        txtVang_TongSL.setText(tongSLVang+"");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, "Ban Nhap Sai Ngay Thang!");
            //Logger.getLogger(Bai_2_3_GiaoDich_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_txtVang_ThemMoiActionPerformed

    private void cbbVang_ThongKeLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbVang_ThongKeLoaiActionPerformed
        // TODO add your handling code here:
        tongTTVang=0;
        tongSLVang=0;
        
        if(cbbVang_ThongKeLoai.getSelectedIndex()==0){
//          cach 1:            
//        txtVang_ThanhTien.setText(String.format("%.0f",tongTTVang1));
//        txtVang_TongSL.setText(tongSLVang1+"");
//          cach 2:
            thongKeVangTotal(listVang);
        }else{
            thongKeVang(listVang);
        }
       
    }//GEN-LAST:event_cbbVang_ThongKeLoaiActionPerformed

    private void cbbTien_ThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTien_ThemMoiActionPerformed
        // TODO add your handling code here:
        try {
            
        String maGD = txtMaGD.getText();
        int soLuong = Integer.parseInt(txtSL.getText());
        double rate = Double.parseDouble(txtRate.getText());
        Date ngay = FormatDate.stringToDate(txtDate.getText());
        String loaiGD = cbbTien_MuaBan.getSelectedItem().toString();
        String loaiTien = cbbTien_NhapLoai.getSelectedItem().toString();
        Bai_2_3_GiaoDich_Tien gdTien = new Bai_2_3_GiaoDich_Tien(loaiGD, maGD, soLuong, rate, ngay, loaiTien);
        listTien.add(gdTien);
        modelTien.addElement(gdTien.toString());
        tongTTTien+=gdTien.ThanhTien();
        tongSLTien+=gdTien.soLuong;
        txtTien_XuatTongSL.setText(tongSLTien+"");
        txtTien_TongThanhTien.setText(String.format("%.0f", tongTTTien));
        } catch(ParseException ex) {
            //Logger.getLogger(Bai_2_3_GiaoDich_Form.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Ban nhap sai ngay thang!");
        }
        
        
        
    }//GEN-LAST:event_cbbTien_ThemMoiActionPerformed

    private void cbbTien_ThongKeLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTien_ThongKeLoaiActionPerformed
        // TODO add your handling code here:
        String loaiGD = cbbTien_ThongKeGD.getSelectedItem().toString();
        String loaiTien = cbbTien_ThongKeLoai.getSelectedItem().toString();
        tongSLTien=0;
        tongTTTien=0;
        if(cbbTien_ThongKeLoai.getSelectedIndex()==0)thongKeTienToTal(listTien, loaiGD);
        else thongKeTien(listTien, loaiGD, loaiTien);
        
    }//GEN-LAST:event_cbbTien_ThongKeLoaiActionPerformed

    private void cbbTien_ThongKeGDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTien_ThongKeGDActionPerformed
        // TODO add your handling code here:
        
       String loaiGD = cbbTien_ThongKeGD.getSelectedItem().toString();
        String loaiTien = cbbTien_ThongKeLoai.getSelectedItem().toString();
        tongSLTien=0;
        tongTTTien=0;
        if(cbbTien_ThongKeLoai.getSelectedIndex()==0)thongKeTienToTal(listTien, loaiGD);
        else thongKeTien(listTien, loaiGD, loaiTien);
        
    }//GEN-LAST:event_cbbTien_ThongKeGDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai_2_3_GiaoDich_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai_2_3_GiaoDich_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai_2_3_GiaoDich_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai_2_3_GiaoDich_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai_2_3_GiaoDich_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbTien_MuaBan;
    private javax.swing.JComboBox<String> cbbTien_NhapLoai;
    private javax.swing.JButton cbbTien_ThemMoi;
    private javax.swing.JComboBox<String> cbbTien_ThongKeGD;
    private javax.swing.JComboBox<String> cbbTien_ThongKeLoai;
    private javax.swing.JComboBox<String> cbbVang_NhapLoai;
    private javax.swing.JComboBox<String> cbbVang_ThongKeLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> lstTien_Xuat;
    private javax.swing.JList<String> lstVang_Xuat;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtMaGD;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtTien_TongThanhTien;
    private javax.swing.JTextField txtTien_XuatTongSL;
    private javax.swing.JTextField txtVang_ThanhTien;
    private javax.swing.JButton txtVang_ThemMoi;
    private javax.swing.JTextField txtVang_TongSL;
    // End of variables declaration//GEN-END:variables
}
